version: "3.9"

services:
  db:
    image: postgres
    container_name: my-helper-db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    container_name: my-helper-rails
#    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  redis:
    image: redis:7.0.0
    container_name: my-helper-redis
    restart: always
    volumes:
      - ./tmp/redis:/data




