version: "3.9"

services:
  db:
    image: postgres
    container_name: my-helper-db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    environment:
      HUB_URL: http://chrome:4444/wd/hub # <-- Add the HUB_URL environment variable
    container_name: my-helper-rails
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - chrome # <-- Link to the chrome container

  redis:
    image: redis:7.0.0
    container_name: my-helper-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis:/data
  chrome:
    image: selenium/standalone-chrome:3.141.59-zirconium # this version should match that of the selenium-webdriver gem (see Gemfile)
    volumes:
      - /dev/shm:/dev/shm
