default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


development:
  <<: *default
  host: db # name of container in docker
  database: my_helper_dev
  user: postgres
  password: password

test:
  <<: *default
  host: db # name of container in docker
  database: my_helper_test #Arbitrary database name
  user: postgres
  password: password

production:
  <<: *default
  database: my_helper_prod #Arbitrary database name
  username: postgres # update this
  password: request.env['DB_PASSWORD'] #Any password
  adapter: postgresql
  encoding: unicode
  pool:  <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>